### PR TITLE
add support for boringssl

### PR DESCRIPTION
**Pull request by kazuho**
Subsumes #432. Builds on top of https://github.com/h2o/h2o/pull/3193.

### CODE REVIEW

**Comment by kazuho** [comment]
@jedisct1 Your review would be appreciated.

Differences from #432 are:
* X25519 is as-is.
* Streaming support has been added to chacha20. Test added for AEAD covers this.
* Logic for chachapoly has been extracted from lib/cifra/chacha20.c and is shared between that and boringssl.
* Added boringssl to CI image and use that for testing.
* Misc. bug fixes.

**Comment by jedisct1** [comment]
Looks good to me! 

Thank you so much, Kazuho!

**Comment by jedisct1** [comment]
Tested on macOS with the current BoringSSL-`HEAD` (`fc524c161e8640e017b0d`) and `zig cc`, everything looks fine! 🎉

**Comment by kazuho** [comment]
Thank you for checking!

**Pull request merged**
