### PR TITLE
fix memory alignment issues re fusion on Windows

### LINKED ISSUE #397: Changes in memory alignment specification break fusion for windows
The changes introduced in  PR "non-temporal aes-gcm engine" #384 require 256 bit alignment, which is poorly supported in Windows. 

The previous version of "fusion.h" specified:
```
typedef struct ptls_fusion_aesecb_context {
    __m128i keys[PTLS_FUSION_AES256_ROUNDS + 1];
    unsigned rounds;
} ptls_fusion_aesecb_context_t;
```
The new version has:
```
typedef struct ptls_fusion_aesecb_context {
    union {
        __m128i m128[PTLS_FUSION_AES256_ROUNDS + 1];
        __m256i m256[PTLS_FUSION_AES256_ROUNDS + 1];
    } keys;
    unsigned rounds;
    uint8_t aesni256;
} __attribute__((aligned(32))) ptls_fusion_aesecb_context_t;
```
The alignment directive `__m128i` is portable, but `__m256i` does not work so well in Windows.

I am fixing it in Picoquic by not using `fusion` for Windows builds.

### PR DESCRIPTION
**Pull request by kazuho**
Closes #397.

### CODE REVIEW

**Comment by kazuho** [comment]
@huitema Would you mind take a look?

I think these changes are sufficient, though I do not mind removing windows support entirely from fusion.

**Comment by huitema** [comment]
The code looks good, the minicrypto and openssl tests pass, but when I try to run `ptlsbench` I get a crash:

image

**Comment by huitema** [comment]
I think the crash happens because the argument `iv` is aligned on 64 bit, not 128 bit. But it is very late here...

**Comment by huitema** [comment]
Tried removing the override of `__attribute()` in `wincompat.h`. Cannot do that. It causes a bunch of syntax errors, e.g.:
```
1>picotls.c
3>c:\users\huite\github\picotls\include\picotls.h(642): error C2146: syntax error: missing ';' before identifier '__attribute__'
3>c:\users\huite\github\picotls\include\picotls.h(642): error C2061: syntax error: identifier '__attribute__'
3>c:\users\huite\github\picotls\include\picotls.h(643): error C2059: syntax error: '}'
3>c:\users\huite\github\picotls\include\picotls.h(791): error C2061: syntax error: identifier 'ptls_log_event_t'
3>c:\users\huite\github\picotls\include\picotls.h(812): error C2059: syntax error: '}'
```

Turns out that "__attribute__" is an extension to the C language defined for GCC and CLANG, but not supported by the VS CC compiler. The memory alignment, if needed, should be through `declspec`, as explained in https://docs.microsoft.com/en-us/cpp/cpp/align-cpp?view=msvc-170.

**Comment by huitema** [comment]
OK, so there are different rules in Visual Studio for C and C++. For C, the documentation (https://docs.microsoft.com/en-us/cpp/c-language/alignment-c?view=msvc-170) says:

`The convenience macros alignof and alignas, defined in <stdalign.h>, map directly to _Alignof and _Alignas, respectively. These macros match the keywords used in C++. So using the macros instead of the C keywords may be helpful for code portability if you share any code between the two languages.`

But then, the compiler cannot find <stdalign.h>. And the pragma _Alignof is not recognized either. Looks like one of those silly border conditions in Microsoft support, that would require a big time investment. Better to just not use `fusion` in Windows. After all, we do have support for `bcrypt` in the code.

**Comment by kazuho** [comment]
Thank you for looking into the issue.

I think the issue can be solved by introducing a wapper around `__attribute__((align))` or `__declspec(align)`. But we do not need to make picotls complex unless there is real need.

**Pull request closed without merging**
