### PR TITLE
External PSK mode

### PR DESCRIPTION
**Pull request by kazuho**
At the moment, external PSK cannot be used together with retry.

Current design of picotls is based on the assumption that (ec)dhe will be used when a HelloRetryRequest is involved. Ideally we should support handshake that uses both retry and external PSK, but that does not need to happen now.

### CODE REVIEW

**Comment by sshock** [comment]
I'm not familiar with hello retries, but do I understand correctly that this PR also enables support for external PSK with initial authentication (so one could use PSK instead of certs)?

**Comment by kazuho** [comment]
@sshock That's correct.

IIRC, HelloRetryRequest is a used for renegotiating the ECDHE algorithm being used in case the client's initial offer did not match what the server can handle. But when PSK is used, it would be unlikely that the client and server to initially disagree on which ECDHE algorithm to be used considering that they've already agreed on the PSK to be used.

That's what the original comment says.

I'm not sure if we are going to merge this PR soon or ever, but I believe it works.

**Comment by sshock** [comment]
> I'm not sure if we are going to merge this PR soon or ever, but I believe it works.

Ok. I may do some testing with it and then I could let you know how it works for me.

**Comment by sshock** [comment]
I created [a new PR](https://github.com/sshock/picotls/pull/1) with these changes rebased against the latest master and all conflicts resolved.

I tried to be careful, but there were a lot of conflicts, including [2 lines of code](https://github.com/sshock/picotls/pull/1#issuecomment-1640704321) that I was unable to find a corresponding location for in the latest code, so I don't know if they are needed or not.

I haven't done a lot of testing yet, but I can confirm that the new pre-shared-key test is passing, both with test-minicrypto.t and test-openssl.t.

**Comment by sshock** [comment]
I modified the `cli` tool to support PSK, but it's seg faulting on the server side after handshake while trying to send a NewSessionTicket.

It's calling `send_session_ticket` and trying to pass `tls->key_share->id` into `encode_session_identifier`, but `tls->key_share` is NULL:

```c
    /* build the raw nsk */
    ret = encode_session_identifier(tls->ctx, &session_id, ticket_age_add, ptls_iovec_init(NULL, 0), tls->key_schedule,
                                    tls->server_name, tls->key_share->id, tls->cipher_suite->id, tls->negotiated_protocol);
```

I'm not a TLS expert (yet 😄), so I'm not even sure if it should be sending a new session ticket, but I believe it is doing that because can_send_session_ticket gets set to true in `server_handle_hello` on this line: `tls->server.can_send_session_ticket = ch->psk.ke_modes != 0;`.

And the reason `tls->key_share` is NULL is probably because `server_handle_hello` deliberately skips setting `tls->key_share = key_share.algorithm;` when the mode is HANDSHAKE_MODE_PSK.

Any advice on how this should be corrected?

**Comment by kazuho** [comment]
Sounds like we have a bug in `send_session_ticket` function, though I think the server doesn't need to send a session ticket when the endpoints already have PSK shared.

By setting `ptls_context_t::ticket_lifetime` to zero, picotls will stop calling `send_session_ticket` (see https://github.com/h2o/picotls/blob/master/lib/picotls.c#L4761). Hopefully that would be the quick fix.

**Comment by sshock** [comment]
> Sounds like we have a bug in `send_session_ticket` function, though I think the server doesn't need to send a session ticket when the endpoints already have PSK shared.
> 
> By setting `ptls_context_t::ticket_lifetime` to zero, picotls will stop calling `send_session_ticket` (see https://github.com/h2o/picotls/blob/master/lib/picotls.c#L4761). Hopefully that would be the quick fix.

Thanks @kazuho.  This workaround worked so that I am no longer encountering a seg fault on the server side.

But now I am running into a PTLS_ALERT_ILLEGAL_PARAMETER on the client side, because the server is sending an early data extension (although the length is 0), but the client isn't expecting that:

```
        case PTLS_EXTENSION_TYPE_EARLY_DATA:
            if (!tls->client.using_early_data) {
                ret = PTLS_ALERT_ILLEGAL_PARAMETER;
                goto Exit;
            }
            skip_early_data = 0;
            break;
```

The server is sending a 0-length early data here in the /* send EncryptedExtensions */ block:

```
            if (tls->pending_handshake_secret != NULL)
                buffer_push_extension(sendbuf, PTLS_EXTENSION_TYPE_EARLY_DATA, {});
```

`tls->pending_handshake_secret` is set to "h", but I haven't been able to find out where that is getting set.

Is there supposed to be a pending_handshake_secret when using PSK, and if so is it supposed to send a 0-length early data in the encrypted extensions?  Any advice on what is wrong with this picture and how to get past it?

**Comment by sshock** [comment]
Here's a comparison matrix of picotls, wolfssl, and openssl:

Screenshot 2023-07-20 at 7 06 12 PM

**Comment by sshock** [comment]
This is the block of code on the openssl server that is failing with picotls client:

```c
    if (PACKET_remaining(&binder) != hashsize) {
        SSLfatal(s, SSL_AD_DECODE_ERROR, SSL_F_TLS_PARSE_CTOS_PSK,
                 SSL_R_BAD_EXTENSION);
        goto err;
    }
```

I think it has something to do with the fact that the PSK Binders that the client is sending is length is 49 (whereas with wolfssl or openssl client it's only length 33).

**Comment by sshock** [comment]
I think I found another issue: picotls needs to use "ext binder" not "res binder" for the binder key label in this case since we are doing external PSK.

**Comment by sshock** [comment]
I made two fixes to the client side, and now the picotls cli client is able to connect and communicate with both wolfssl and openssl servers:
* [Use correct binder key label(https://github.com/sshock/picotls/pull/1/commits/fba3d962d1fb49870b50be0bede48a34fd06ed9a)
* [Default to SHA-256 with external PSK](https://github.com/sshock/picotls/pull/1/commits/b6b3c04b809b988db54d57bfcaabae12b257f136)

I'll work on the server side tomorrow.

**Comment by sshock** [comment]
I made the following fixes to the server side today:
* [Use correct binder key label on server
](https://github.com/sshock/picotls/pull/1/commits/9912af6af5d9ebf749fbd4f46b363bc221717189)
* [Fix bug that was causing server to send early data indicator](https://github.com/sshock/picotls/pull/1/commits/7782e0a28956ab56a97ea4ff5517df905e43b6e5)
* [Select PSK compatible cipher suite on server](https://github.com/sshock/picotls/pull/1/commits/ea44c61659d84b0a19e9dc9f17d7491d09194972) (I would love feedback on how to do this in a cleaner way)
* [Only accept early data if using the first PSK](https://github.com/sshock/picotls/pull/1/commits/415f5c4ebf0095686bf925cae9109d8e6cec7db2) (may not have needed this; see commit comment)

As a result, things have improved in my interop testing:

interop after

**Comment by sshock** [comment]
Good news.  I was able to do more testing with wolfssl and openssl clients and get them working against picotls server with only one real failure remaining in one scenario (when wolfssl presents both ke modes).  But at this point I'm ready to call it good, and that could even be a bug in wolfssl.

latest matrix

@kazuho could we consider merging [my PR](https://github.com/sshock/picotls/pull/1)?  It would be great if I didn't have to maintain it in a fork.

**Comment by kazuho** [comment]
@sshock Thank you for all the work and coming up with a fix. I'll take a look at your code next work.

**Comment by sshock** [comment]
should we close this out since we have #481 ?

**Pull request closed without merging**
