### PR TITLE
disallow 0-RTT when the reported ticket age is too large, otherwise the time window of replay becomes big

### LINKED ISSUE #208: improve (or provide hook to customize) 0-RTT ticket replay detection
The rule we have now is very lax. We accept 0-RTT unless we see an unexpectedly old ticket (i.e., issued more than 10 seconds ago).
```
            int64_t delta = (now - issue_at) - (identity->obfuscated_ticket_age - age_add);
            if (delta <= PTLS_EARLY_DATA_MAX_DELAY)
                *accept_early_data = 1;
```

This is fine when the `max_early_data_size` is small (compared to the size of the TCP receive buffer) and if the application protocol has a way to delay the processing of 0-RTT data (e.g., HTTP 425).

However, considering the fact that picotls might be used for application protocols other than HTTP, it's worth considering tightening the limits (we do not check the lower bound at all!), or providing a hook to customize reuse detection.

### PR DESCRIPTION
**Pull request by kazuho**
closes #208.

@huitema I need to add tests, but I'd appreciate it if you could check if the patch works.

### CODE REVIEW

**Comment by huitema** [comment]
I have a question on the programming model. Currently, the client application receives the tickets with the "save ticket" callback, and the provides the ticket to picotls by documenting `ctx->handshake_properties.client.session_ticket`. The verification algorithm supposes that the obfuscated age is updated to reflect the delay between time of save and time of use. Who is in charge of doing that? Is it the picotls stack, or is it the application?

**Comment by huitema** [comment]
Also, the title of the PR is somewhat misleading. We don't want to detect broken clocks, we want to detect replay of the client first flight by adversaries. The broken clocks would prevent us from doing that.

**Comment by kazuho** [comment]
@huitema Applications do not need to take care of obfuscated ticket age, or anything. Just treat the contents passed to the save_ticket function as a blob, and supply it to the TLS handshake using `ptls_handshake_properties_t`.

It works because what is contained in the blob is not just the session ticket itself. Things like resumption master secret, time of receipt, previously-selected cipher-suites are embedded. See `client_handle_new_session_ticket`.

**Comment by kazuho** [comment]
@huitema Changed the title. While I still consider this to be an issue only when either endpoint (or both) have inaccurate clock, I think the updated title better clarifies the risk we are trying to eliminate.

Please let me know if you prefer something else.

**Comment by huitema** [comment]
The title is fine.

**Pull request merged**
