### PR TITLE
provide hook to associate application data to `ptls_t`

### PR DESCRIPTION
**Pull request by kazuho**
```
ptls_t *tls;
void *my_data;
...

// set
*ptls_get_data_ptr(tls) = my_data;

// get
my_data = *ptls_get_data_ptr(tls);
```

### CODE REVIEW

**Comment by kazuho** [comment]
@larseggert My understanding is that you need to access to per-connection data in your `save_ticket` callback, and your preference is having a "user pointer" rather than creating a per-connection context.

Does the API provided by this PR suffice your needs?

@huitema Do you have any concerns?

**Comment by larseggert** [comment]
Looks good. This would of course also work with the `encrypt_ticket` callback then?

**Comment by kazuho** [comment]
@larseggert
> This would of course also work with the `encrypt_ticket` callback then?

Yes. `encrypt_ticket` accepts `ptls_t *` as an argument. You can call `ptls_get_data_ptr` against the argument.

**Comment by bkchr** [comment]
I like the solution and that will help to implement the verify certificate callback in picoquic!

**Comment by kazuho** [comment]
@larseggert @bkchr Thank you for your responses. Let's merge then.

**Pull request merged**
