### PR TITLE
Modularize cifra

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Comment by larseggert** [comment]
The one remaining issue is that this enables both `ptls_minicrypto_aes128gcmsha256` and `ptls_minicrypto_aes256gcmsha384`. Can you see a clean way to only provide the one that is required?

**Comment by larseggert** [comment]
The CI fail seems to be due to a Travis hiccup (I am getting seriously annoyed at Travis...)

**Comment by huitema** [comment]
When I try to compile this branch on Windows, I get the following set of errors:
```
1>------ Build started: Project: picotlsvs, Configuration: Debug x64 ------
2>------ Build started: Project: testopenssl, Configuration: Debug x64 ------
3>------ Build started: Project: ptlsbench, Configuration: Debug x64 ------
2>picotest.c
3>   Creating library C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\ptlsbench.lib and object C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\ptlsbench.exp
3>ptlsbench.obj : error LNK2001: unresolved external symbol ptls_minicrypto_aes128gcm
3>ptlsbench.obj : error LNK2001: unresolved external symbol ptls_minicrypto_aes256gcm
3>ptlsbench.obj : error LNK2001: unresolved external symbol ptls_minicrypto_chacha20poly1305
3>ptlsbench.obj : error LNK2001: unresolved external symbol ptls_minicrypto_sha256
3>ptlsbench.obj : error LNK2001: unresolved external symbol ptls_minicrypto_sha384
3>C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\ptlsbench.exe : fatal error LNK1120: 5 unresolved externals
3>Done building project "ptlsbench.vcxproj" -- FAILED.
1>   Creating library C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\picotlsvs.lib and object C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\picotlsvs.exp
1>picotls.lib(cifra.obj) : error LNK2001: unresolved external symbol ptls_minicrypto_aes128gcmsha256
1>picotls.lib(cifra.obj) : error LNK2001: unresolved external symbol ptls_minicrypto_aes256gcmsha384
1>picotls.lib(cifra.obj) : error LNK2001: unresolved external symbol ptls_minicrypto_chacha20poly1305sha256
1>C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\picotlsvs.exe : fatal error LNK1120: 3 unresolved externals
1>Done building project "picotlsvs.vcxproj" -- FAILED.
2>openssl.c
2>picotls.c
2>Generating Code...
2>   Creating library C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\testopenssl.lib and object C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\testopenssl.exp
2>openssl.obj : error LNK2001: unresolved external symbol ptls_minicrypto_x25519
2>picotls.obj : error LNK2001: unresolved external symbol ptls_minicrypto_x25519
2>picotls.obj : error LNK2001: unresolved external symbol ptls_minicrypto_aes128ctr
2>picotls.lib(cifra.obj) : error LNK2001: unresolved external symbol ptls_minicrypto_aes128gcmsha256
2>picotls.lib(cifra.obj) : error LNK2001: unresolved external symbol ptls_minicrypto_aes256gcmsha384
2>picotls.lib(cifra.obj) : error LNK2001: unresolved external symbol ptls_minicrypto_chacha20poly1305sha256
2>C:\Users\huite\Documents\GitHub\picotls-lars\picotlsvs\x64\Debug\testopenssl.exe : fatal error LNK1120: 5 unresolved externals
2>Done building project "testopenssl.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 4 up-to-date, 0 skipped ==========
```

**Comment by huitema** [comment]
@larseggert How do I use, for example `ptls_minicrypto_x25519` in the benchmark ptlsbench? Do I need an extra include file?

**Comment by larseggert** [comment]
@huitema I don't quite follow. `ptlsbench` doesn't run x25519 for me at all, even on master?

**Comment by kazuho** [comment]
@larseggert 
> The one remaining issue is that this enables both ptls_minicrypto_aes128gcmsha256 and ptls_minicrypto_aes256gcmsha384. Can you see a clean way to only provide the one that is required?

I think something along the lines of below might work:
* create lib/cifra/aes.h (notice the extension)
    * move key-size-independent structs, functions into this file
    * functions being should be marked as `static inline`
* create lib/cifra/aes128.c, lib/cifra/aes256.c
    * have key-size-dependent functions in these files
    * include lib/cifra/aes.h to use the common structs, functions

**Comment by larseggert** [comment]
@huitema do your link errors go away of you link the C files under `lib/cifra`?

**Comment by larseggert** [comment]
@kazuho Thanks for the suggestion! I updated the PR and this seems to work.

**Comment by huitema** [comment]
I think there is a problem with the way the linking is organized in the VS solution. The difference is that the VS solution builds libraries and then links them, so a given module is only compiled once. The CMake defines groups of files, and compiles them for each of the library modules. I need some time to study that.

**Comment by huitema** [comment]
The changes to the VS solution adopt a library structure parallel to `CMakeList.txt`. It compiles, and `ptlsbench` work. However, I got an error when running `picotlsvs` -- will try debug that later.

**Comment by huitema** [comment]
When running tests on Windows, I get an error when executing the test:
```
subtest("full-handshake", test_full_handshake);
```
The report is:
```
Run-Time Check Failure #2 - Stack around the variable 'mod_multiple' was corrupted.
```
The stack is:
```
>	testopenssl.exe!uECC_vli_mmod(unsigned __int64 * result, unsigned __int64 * product, const unsigned __int64 * mod, char num_words) Line 604	C
 	testopenssl.exe!uECC_vli_modMult(unsigned __int64 * result, const unsigned __int64 * left, const unsigned __int64 * right, const unsigned __int64 * mod, char num_words) Line 615	C
 	testopenssl.exe!uECC_sign_with_k(const unsigned char * private_key, const unsigned char * message_hash, unsigned int hash_size, unsigned __int64 * k, unsigned char * signature, const uECC_Curve_t * curve) Line 1275	C
 	testopenssl.exe!uECC_sign(const unsigned char * private_key, const unsigned char * message_hash, unsigned int hash_size, unsigned char * signature, const uECC_Curve_t * curve) Line 1319	C
 	testopenssl.exe!secp256r1sha256_sign(st_ptls_sign_certificate_t * _self, st_ptls_t * tls, wchar_t * selected_algorithm, st_ptls_buffer_t * outbuf, st_ptls_iovec_t input, const unsigned short * algorithms, unsigned __int64 num_algorithms) Line 161	C
 	testopenssl.exe!sign_certificate(st_ptls_sign_certificate_t * self, st_ptls_t * tls, wchar_t * selected_algorithm, st_ptls_buffer_t * output, st_ptls_iovec_t input, const unsigned short * algorithms, unsigned __int64 num_algorithms) Line 798	C
 	testopenssl.exe!send_certificate_and_certificate_verify(st_ptls_t * tls, st_ptls_message_emitter_t * emitter, st_ptls_signature_algorithms_t * signature_algorithms, st_ptls_iovec_t context, const char * context_string, int push_status_request) Line 2541	C
 	testopenssl.exe!server_handle_hello(st_ptls_t * tls, st_ptls_message_emitter_t * emitter, st_ptls_iovec_t message, st_ptls_handshake_properties_t * properties) Line 3887	C
 	testopenssl.exe!handle_handshake_message(st_ptls_t * tls, st_ptls_message_emitter_t * emitter, st_ptls_iovec_t message, int is_end_of_record, st_ptls_handshake_properties_t * properties) Line 4299	C
 	testopenssl.exe!handle_handshake_record(st_ptls_t * tls, int(*)(st_ptls_t *, st_ptls_message_emitter_t *, st_ptls_iovec_t, int, st_ptls_handshake_properties_t *) cb, st_ptls_message_emitter_t * emitter, st_ptls_record_t * rec, st_ptls_handshake_properties_t * properties) Line 4407	C
 	testopenssl.exe!handle_input(st_ptls_t * tls, st_ptls_message_emitter_t * emitter, st_ptls_buffer_t * decryptbuf, const void * input, unsigned __int64 * inlen, st_ptls_handshake_properties_t * properties) Line 4487	C
 	testopenssl.exe!ptls_handshake(st_ptls_t * tls, st_ptls_buffer_t * _sendbuf, const void * input, unsigned __int64 * inlen, st_ptls_handshake_properties_t * properties) Line 4561	C
 	testopenssl.exe!test_handshake(st_ptls_iovec_t ticket, int mode, int expect_ticket, int check_ch, int require_client_authentication) Line 631	C
 	testopenssl.exe!test_full_handshake_impl(int require_client_authentication) Line 814	C
 	testopenssl.exe!test_full_handshake() Line 838	C
 	testopenssl.exe!subtest(const char * name, void(*)() cb) Line 98	C
 	testopenssl.exe!test_all_handshakes() Line 1419	C
 	testopenssl.exe!subtest(const char * name, void(*)() cb) Line 98	C
 	testopenssl.exe!test_picotls() Line 1459	C
 	testopenssl.exe!subtest(const char * name, void(*)() cb) Line 98	C
 	testopenssl.exe!main(int argc, char * * argv) Line 343	C
```
Any idea what can cause this issue?

**Comment by larseggert** [comment]
I don't know why CI fails. What does "Parse errors: No plan found in TAP output" mean?

**Comment by huitema** [comment]
I think I found the offending line in `uECC_vli_modSub()` -- line 585 in `uECC.c`:
```
    if (bit_shift > 0) {
        for(index = 0; index < (uECC_word_t)num_words; ++index) {
            mod_multiple[word_shift + index] = (mod[index] << bit_shift) | carry;
            carry = mod[index] >> (uECC_WORD_BITS - bit_shift);
        }
    } else {
        uECC_vli_set(mod_multiple + word_shift, mod, num_words);
    }
```
When I watch the execution, `num_words` is set to 4 (same as `uECC_MAX_WORDS`), `bit_shift` to 0, and `word_shift` to 8. The call to `uECC_vli_set` will write at position `mod_multiple+8`, which is past the memory allocation for `mod_multiple`, and thus corrupts the stack.

Any idea what the fix should be?

**Comment by huitema** [comment]
OK, I found the bug that caused the crash -- over aggressive casting to (uint8_t) was causing return of 0 instead of 512. All tests are passing now for the windows build.

**Comment by larseggert** [comment]
@kazuho IMO this looks OK to merge

**Comment by kazuho** [comment]
@huitema I've moved out the PRNG into dedicated source file (lib/cifra/random.c). Would you mind updating the build configuration for Windows?

**Comment by huitema** [comment]
@kazuho Just pushed the change to add random.c to the VS project. Tests work.

**Comment by kazuho** [comment]
@huitema Thank you. Merged.

**Pull request merged**
