### PR TITLE
[HPKE] implement basic functionality

### PR DESCRIPTION
**Pull request by kazuho**
Implements basic functionality of HPKE (RFC 9180) which is the basis of ECH.

### CODE REVIEW

**Comment by huitema** [comment]
I think you mean RFC 9180. 8180 is about IPv6...

**Comment by huitema** [comment]
I am looking at the failures in windows builds. 

lib/ptlsbcrypt.c:
- The definitions of `ptls_aead_algorithm_t` and `ptls_hash_algorithm_t` have changed, and the constant declarations need to be modified accordingly.

lib/picotls.c:
- Various warnings about integer type mismatch (vs compiler is very picky about that). For example, use:
```
static void build_tls12_aad(uint8_t *aad, uint8_t type, uint64_t seq, uint16_t length)
{
    for (size_t i = 0; i < 8; ++i)
        aad[i] = (uint8_t)(seq >> (56 - i * 8));
    aad[8] = type;
    aad[9] = PTLS_RECORD_VERSION_MAJOR;
    aad[10] = PTLS_RECORD_VERSION_MINOR;
    aad[11] = (uint8_t)(length >> 8);
    aad[12] = (uint8_t)length;
}
```

t/picotls.c:
- In new test, initialize structures with ` = { 0}` instead of ` = {}`.

I could take a pass at that, but will have to be later this week -- not that much time during the IETF.

**Comment by kazuho** [comment]
@huitema Thank you for the quick review. Indeed, we have issues on the Windows-side.

* Thanks to CI, I can fix all the compile errors.
* Regarding warnings, it comes from existing code in CI, I will handle them separately.
* What I think I need your help is to add lib/hpke.c to the core library, otherwise the linker would complain.

All that said, no hurries. This PR is to be kept open until we add the new ECH code. I made this separate PR for the ease of review.

**Comment by huitema** [comment]
Please check PR #435. It fixes the VS issues in a minimal way, makes sure compile and tests work.

**Pull request merged**
